#!/usr/bin/env bash
set -euo pipefail

ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
cd "$ROOT"

RUN_ID="${RUN_ID:-stageB_v256_target_project_component_support_$(TZ=Asia/Shanghai date '+%Y%m%d_%H%M%S_bjt')}"
GPU="${GPU:-0}"
LOG_DIR="${LOG_DIR:-$ROOT/exp/stageB/logs/377_stageB_v256_target_project_component_support_${RUN_ID}}"
mkdir -p "$LOG_DIR"

NOHUP_LOG="$LOG_DIR/nohup.log"
PYTHON_BIN="${PYTHON_BIN:-/opt/miniconda3/envs/ictrl/bin/python}"

BASE_V250_EXP="$ROOT/exp/stageB/377_hulk_light_v250b_gapaware_component_support_9h_stageB_v250_gapaware_component_support_9h_20260515_002233_bjt"
BASE_CKPT_DEFAULT="$BASE_V250_EXP/ckpt144950.pth"
BASE_ITER_DEFAULT="144950"

env \
  EXPERIMENT_VERSION="v256" \
  EXPERIMENT_SLUG="target_project_component_support" \
  TRAIN_NAME="v256a_target_project_component_support" \
  LOG_PREFIX="377_stageB_v256_target_project_component_support" \
  RENDER_TAG="v256" \
  PURPOSE="v256 target-project component support: place explicit support Gaussians by birth-camera target pixel unprojection instead of heuristic screen-direction length" \
  RUN_ID="$RUN_ID" \
  GPU="$GPU" \
  LOG_DIR="$LOG_DIR" \
  WAIT_FOR_FREE_GPU=1 \
  DO_RENDER=1 \
  PYTHON_BIN="$PYTHON_BIN" \
  BASE_CKPT="$BASE_CKPT_DEFAULT" \
  BASE_ITER="$BASE_ITER_DEFAULT" \
  STAGEB_ITERATIONS=360 \
  STAGEB_CHECKPOINT_STEPS="360" \
  RENDER_CHECKPOINT_STEPS="360" \
  TEST_INTERVAL=1000 \
  DENSIFY_FROM_STEP=20 \
  DENSIFY_UNTIL_STEP=361 \
  DENSIFY_INTERVAL=120 \
  DENSIFY_GRAD_THRESHOLD=0.00110 \
  TRAIN_VIEWS="[1,2,3,4,5,6,7,8,9,10,11,12]" \
  VAL_VIEWS="[21,22,23]" \
  TEST_VIEWS="[21,22,23]" \
  TRAIN_FRAMES="[0,570,1]" \
  VAL_FRAMES="[0,570,60]" \
  TEST_FRAMES="[0,570,60]" \
  RENDER_TEST_VIEWS="[21,22,23]" \
  RENDER_TEST_FRAMES="[0,570,60]" \
  RENDER_SPLIT_DIR="test-view" \
  BINDING_MAPS="[layer,region,compact_semantic,body_prob,soft_prob,cloth_prob,semantic,temporal,thin,boundary_support]" \
  MONTAGE_PANELS="gt render layer region body_prob cloth_prob compact_semantic boundary_support thin semantic" \
  BINDING_DENSIFY_DISABLE_CLONE=true \
  BINDING_DENSIFY_DISABLE_SPLIT=true \
  BOUNDARY_COMPONENT_SUPPORT_COVERAGE_VERBOSE=true \
  BOUNDARY_COMPONENT_SUPPORT_PROJECTION_AUDIT_VERBOSE=true \
  BOUNDARY_COMPONENT_SUPPORT_TARGET_PROJECT_ENABLE=true \
  BOUNDARY_COMPONENT_SUPPORT_TARGET_PROJECT_VERBOSE=true \
  BOUNDARY_COMPONENT_SUPPORT_USE_TARGET_OFFSETS=true \
  BOUNDARY_COMPONENT_SUPPORT_TARGET_PROJECT_OFFSET_MIN=0.000001 \
  BOUNDARY_COMPONENT_SUPPORT_TARGET_PROJECT_OFFSET_MAX=0.080 \
  BOUNDARY_COMPONENT_SUPPORT_TARGET_OFFSET_MAX=0.080 \
  BOUNDARY_COMPONENT_SUPPORT_ACCUMULATE_PENDING=true \
  BOUNDARY_COMPONENT_SUPPORT_PENDING_MAX_VIEWS=4 \
  BOUNDARY_COMPONENT_SUPPORT_PENDING_MAX_POINTS=96 \
  BOUNDARY_COMPONENT_SUPPORT_PENDING_VERBOSE=true \
  BOUNDARY_COMPONENT_SUPPORT_MAX_POINTS=72 \
  BOUNDARY_COMPONENT_SUPPORT_UNIQUE_PARENT=false \
  BOUNDARY_COMPONENT_SUPPORT_RESIDUAL_THRESHOLD=0.50 \
  BOUNDARY_COMPONENT_SUPPORT_MIN_AREA=18 \
  BOUNDARY_COMPONENT_SUPPORT_MAX_COMPONENTS=12 \
  BOUNDARY_COMPONENT_SUPPORT_POINTS_PER_COMPONENT=2 \
  BOUNDARY_COMPONENT_SUPPORT_MAX_POINTS_PER_VIEW=24 \
  BOUNDARY_COMPONENT_SUPPORT_ANCHOR_SEARCH_RADIUS=24.0 \
  BOUNDARY_COMPONENT_SUPPORT_ANCHOR_FALLBACK_RADIUS=40.0 \
  BOUNDARY_COMPONENT_SUPPORT_MAX_SCREEN_GAP=38.0 \
  BOUNDARY_COMPONENT_SUPPORT_ANCHOR_BOUNDARY_MIN=0.08 \
  BOUNDARY_COMPONENT_SUPPORT_ANCHOR_OVER_MAX=0.22 \
  BOUNDARY_COMPONENT_SUPPORT_ANCHOR_OVER_REJECT_STRICT=false \
  BOUNDARY_COMPONENT_SUPPORT_ANCHOR_OVER_PENALTY_WEIGHT=0.55 \
  BOUNDARY_COMPONENT_SUPPORT_OFFSET_SCALE=0.60 \
  BOUNDARY_COMPONENT_SUPPORT_OFFSET_MIN=0.0012 \
  BOUNDARY_COMPONENT_SUPPORT_OFFSET_MAX=0.034 \
  BOUNDARY_COMPONENT_SUPPORT_SCREEN_GAP_OFFSET_SCALE=0.95 \
  BOUNDARY_COMPONENT_SUPPORT_SCREEN_GAP_RADIUS_MIN=1.5 \
  BOUNDARY_COMPONENT_SUPPORT_SCREEN_GAP_RATIO_MAX=2.5 \
  BOUNDARY_COMPONENT_SUPPORT_SCREEN_GAP_OFFSET_MAX=0.034 \
  BOUNDARY_COMPONENT_SUPPORT_CHILD_OPACITY_FACTOR=1.00 \
  BOUNDARY_COMPONENT_SUPPORT_CHILD_OPACITY_FLOOR=0.050 \
  BOUNDARY_COMPONENT_SUPPORT_CHILD_OPACITY_CEILING=0.44 \
  BOUNDARY_COMPONENT_SUPPORT_CHILD_SCALE_FACTOR=0.72 \
  BOUNDARY_SUPPORT_PROJECTOR_ENABLE=false \
  BOUNDARY_SUPPORT_PROJECTOR_VERBOSE=true \
  BOUNDARY_SUPPORT_PROJECTOR_INNER_ENABLE=false \
  BOUNDARY_SUPPORT_PROJECTOR_OUTER_ENABLE=false \
  setsid bash "$ROOT/tools/run_377_stageB_v248_boundary_component_support_serial.sh" \
  > "$NOHUP_LOG" 2>&1 &

PID=$!
echo "$PID" > "$LOG_DIR/launcher.pid"

{
  echo "RUN_ID=$RUN_ID"
  echo "PID=$PID"
  echo "GPU=$GPU"
  echo "LOG_DIR=$LOG_DIR"
  echo "NOHUP_LOG=$NOHUP_LOG"
  echo "BASE_CKPT=$BASE_CKPT_DEFAULT"
  echo "EXPECTED_FINAL_CKPT=$ROOT/exp/stageB/377_hulk_light_v256a_target_project_component_support_${RUN_ID}/ckpt145310.pth"
  echo "EVENTS=$LOG_DIR/events.tsv"
  echo "SUMMARY=$LOG_DIR/summary.tsv"
  echo "START_BJT=$(TZ=Asia/Shanghai date '+%F %T BJT')"
} | tee "$LOG_DIR/launcher_info.txt"
