#!/usr/bin/env bash
set -euo pipefail

ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
cd "$ROOT"

RUN_ID="${RUN_ID:-stageB_v253_support_activation_probe_$(TZ=Asia/Shanghai date '+%Y%m%d_%H%M%S_bjt')}"
GPU="${GPU:-0}"
LOG_DIR="${LOG_DIR:-$ROOT/exp/stageB/logs/377_stageB_v253_support_activation_probe_${RUN_ID}}"
mkdir -p "$LOG_DIR"

NOHUP_LOG="$LOG_DIR/nohup.log"
BASE_V250_EXP="$ROOT/exp/stageB/377_hulk_light_v250b_gapaware_component_support_9h_stageB_v250_gapaware_component_support_9h_20260515_002233_bjt"

env \
  EXPERIMENT_VERSION="v253" \
  EXPERIMENT_SLUG="support_activation_probe" \
  TRAIN_NAME="v253b_support_activation_probe" \
  LOG_PREFIX="377_stageB_v253_support_activation_probe" \
  RENDER_TAG="v253" \
  PURPOSE="v253 support activation probe: disable outer shrink and strengthen component support opacity/scale to test whether appended support can expand binary render support" \
  RUN_ID="$RUN_ID" \
  GPU="$GPU" \
  WAIT_FOR_FREE_GPU="${WAIT_FOR_FREE_GPU:-1}" \
  DO_RENDER="${DO_RENDER:-1}" \
  PYTHON_BIN="${PYTHON_BIN:-/opt/miniconda3/envs/ictrl/bin/python}" \
  BASE_CKPT="${BASE_CKPT:-$BASE_V250_EXP/ckpt144950.pth}" \
  BASE_ITER="${BASE_ITER:-144950}" \
  STAGEB_ITERATIONS="${STAGEB_ITERATIONS:-240}" \
  STAGEB_CHECKPOINT_STEPS="${STAGEB_CHECKPOINT_STEPS:-120,240}" \
  RENDER_CHECKPOINT_STEPS="${RENDER_CHECKPOINT_STEPS:-120,240}" \
  TEST_INTERVAL="${TEST_INTERVAL:-1000}" \
  DENSIFY_FROM_STEP="${DENSIFY_FROM_STEP:-20}" \
  DENSIFY_UNTIL_STEP="${DENSIFY_UNTIL_STEP:-240}" \
  DENSIFY_INTERVAL="${DENSIFY_INTERVAL:-120}" \
  DENSIFY_GRAD_THRESHOLD="${DENSIFY_GRAD_THRESHOLD:-0.00110}" \
  BINDING_MAPS="${BINDING_MAPS:-[layer,region,compact_semantic,body_prob,soft_prob,cloth_prob,semantic,temporal,thin,boundary_support]}" \
  MONTAGE_PANELS="${MONTAGE_PANELS:-gt render layer region body_prob cloth_prob compact_semantic boundary_support thin semantic}" \
  BOUNDARY_COMPONENT_SUPPORT_ACCUMULATE_PENDING="${BOUNDARY_COMPONENT_SUPPORT_ACCUMULATE_PENDING:-true}" \
  BOUNDARY_COMPONENT_SUPPORT_PENDING_MAX_VIEWS="${BOUNDARY_COMPONENT_SUPPORT_PENDING_MAX_VIEWS:-4}" \
  BOUNDARY_COMPONENT_SUPPORT_PENDING_MAX_POINTS="${BOUNDARY_COMPONENT_SUPPORT_PENDING_MAX_POINTS:-96}" \
  BOUNDARY_COMPONENT_SUPPORT_PENDING_VERBOSE="${BOUNDARY_COMPONENT_SUPPORT_PENDING_VERBOSE:-true}" \
  BOUNDARY_COMPONENT_SUPPORT_MAX_POINTS="${BOUNDARY_COMPONENT_SUPPORT_MAX_POINTS:-64}" \
  BOUNDARY_COMPONENT_SUPPORT_UNIQUE_PARENT="${BOUNDARY_COMPONENT_SUPPORT_UNIQUE_PARENT:-true}" \
  BOUNDARY_COMPONENT_SUPPORT_RESIDUAL_THRESHOLD="${BOUNDARY_COMPONENT_SUPPORT_RESIDUAL_THRESHOLD:-0.50}" \
  BOUNDARY_COMPONENT_SUPPORT_MIN_AREA="${BOUNDARY_COMPONENT_SUPPORT_MIN_AREA:-18}" \
  BOUNDARY_COMPONENT_SUPPORT_MAX_COMPONENTS="${BOUNDARY_COMPONENT_SUPPORT_MAX_COMPONENTS:-12}" \
  BOUNDARY_COMPONENT_SUPPORT_POINTS_PER_COMPONENT="${BOUNDARY_COMPONENT_SUPPORT_POINTS_PER_COMPONENT:-2}" \
  BOUNDARY_COMPONENT_SUPPORT_MAX_POINTS_PER_VIEW="${BOUNDARY_COMPONENT_SUPPORT_MAX_POINTS_PER_VIEW:-24}" \
  BOUNDARY_COMPONENT_SUPPORT_ANCHOR_SEARCH_RADIUS="${BOUNDARY_COMPONENT_SUPPORT_ANCHOR_SEARCH_RADIUS:-24.0}" \
  BOUNDARY_COMPONENT_SUPPORT_ANCHOR_FALLBACK_RADIUS="${BOUNDARY_COMPONENT_SUPPORT_ANCHOR_FALLBACK_RADIUS:-40.0}" \
  BOUNDARY_COMPONENT_SUPPORT_MAX_SCREEN_GAP="${BOUNDARY_COMPONENT_SUPPORT_MAX_SCREEN_GAP:-38.0}" \
  BOUNDARY_COMPONENT_SUPPORT_ANCHOR_BOUNDARY_MIN="${BOUNDARY_COMPONENT_SUPPORT_ANCHOR_BOUNDARY_MIN:-0.08}" \
  BOUNDARY_COMPONENT_SUPPORT_ANCHOR_OVER_MAX="${BOUNDARY_COMPONENT_SUPPORT_ANCHOR_OVER_MAX:-0.22}" \
  BOUNDARY_COMPONENT_SUPPORT_ANCHOR_OVER_REJECT_STRICT="${BOUNDARY_COMPONENT_SUPPORT_ANCHOR_OVER_REJECT_STRICT:-false}" \
  BOUNDARY_COMPONENT_SUPPORT_ANCHOR_OVER_PENALTY_WEIGHT="${BOUNDARY_COMPONENT_SUPPORT_ANCHOR_OVER_PENALTY_WEIGHT:-0.55}" \
  BOUNDARY_COMPONENT_SUPPORT_OFFSET_SCALE="${BOUNDARY_COMPONENT_SUPPORT_OFFSET_SCALE:-0.60}" \
  BOUNDARY_COMPONENT_SUPPORT_OFFSET_MIN="${BOUNDARY_COMPONENT_SUPPORT_OFFSET_MIN:-0.0012}" \
  BOUNDARY_COMPONENT_SUPPORT_OFFSET_MAX="${BOUNDARY_COMPONENT_SUPPORT_OFFSET_MAX:-0.034}" \
  BOUNDARY_COMPONENT_SUPPORT_SCREEN_GAP_OFFSET_SCALE="${BOUNDARY_COMPONENT_SUPPORT_SCREEN_GAP_OFFSET_SCALE:-0.95}" \
  BOUNDARY_COMPONENT_SUPPORT_SCREEN_GAP_RADIUS_MIN="${BOUNDARY_COMPONENT_SUPPORT_SCREEN_GAP_RADIUS_MIN:-1.5}" \
  BOUNDARY_COMPONENT_SUPPORT_SCREEN_GAP_RATIO_MAX="${BOUNDARY_COMPONENT_SUPPORT_SCREEN_GAP_RATIO_MAX:-2.5}" \
  BOUNDARY_COMPONENT_SUPPORT_SCREEN_GAP_OFFSET_MAX="${BOUNDARY_COMPONENT_SUPPORT_SCREEN_GAP_OFFSET_MAX:-0.034}" \
  BOUNDARY_COMPONENT_SUPPORT_CHILD_OPACITY_FACTOR="${BOUNDARY_COMPONENT_SUPPORT_CHILD_OPACITY_FACTOR:-0.95}" \
  BOUNDARY_COMPONENT_SUPPORT_CHILD_OPACITY_FLOOR="${BOUNDARY_COMPONENT_SUPPORT_CHILD_OPACITY_FLOOR:-0.045}" \
  BOUNDARY_COMPONENT_SUPPORT_CHILD_OPACITY_CEILING="${BOUNDARY_COMPONENT_SUPPORT_CHILD_OPACITY_CEILING:-0.42}" \
  BOUNDARY_COMPONENT_SUPPORT_CHILD_SCALE_FACTOR="${BOUNDARY_COMPONENT_SUPPORT_CHILD_SCALE_FACTOR:-0.72}" \
  BOUNDARY_SUPPORT_PROJECTOR_ENABLE="${BOUNDARY_SUPPORT_PROJECTOR_ENABLE:-false}" \
  BOUNDARY_SUPPORT_PROJECTOR_VERBOSE="${BOUNDARY_SUPPORT_PROJECTOR_VERBOSE:-true}" \
  BOUNDARY_SUPPORT_PROJECTOR_INNER_ENABLE="${BOUNDARY_SUPPORT_PROJECTOR_INNER_ENABLE:-false}" \
  BOUNDARY_SUPPORT_PROJECTOR_OUTER_ENABLE="${BOUNDARY_SUPPORT_PROJECTOR_OUTER_ENABLE:-false}" \
  BOUNDARY_SUPPORT_PROJECTOR_INNER_MAX_POINTS="${BOUNDARY_SUPPORT_PROJECTOR_INNER_MAX_POINTS:-0}" \
  BOUNDARY_SUPPORT_PROJECTOR_INNER_MAX_RATIO="${BOUNDARY_SUPPORT_PROJECTOR_INNER_MAX_RATIO:-0.0}" \
  BOUNDARY_SUPPORT_PROJECTOR_OUTER_MAX_POINTS="${BOUNDARY_SUPPORT_PROJECTOR_OUTER_MAX_POINTS:-0}" \
  BOUNDARY_SUPPORT_PROJECTOR_OUTER_MAX_RATIO="${BOUNDARY_SUPPORT_PROJECTOR_OUTER_MAX_RATIO:-0.0}" \
  BOUNDARY_SUPPORT_PROJECTOR_OUTER_MAX_POINTS_PER_LINEAGE="${BOUNDARY_SUPPORT_PROJECTOR_OUTER_MAX_POINTS_PER_LINEAGE:-1}" \
  BOUNDARY_SUPPORT_PROJECTOR_OVER_THRESHOLD="${BOUNDARY_SUPPORT_PROJECTOR_OVER_THRESHOLD:-0.12}" \
  BOUNDARY_SUPPORT_PROJECTOR_BOUNDARY_THRESHOLD="${BOUNDARY_SUPPORT_PROJECTOR_BOUNDARY_THRESHOLD:-0.04}" \
  BOUNDARY_SUPPORT_PROJECTOR_OUTER_UNDER_PROTECT_THRESHOLD="${BOUNDARY_SUPPORT_PROJECTOR_OUTER_UNDER_PROTECT_THRESHOLD:-0.18}" \
  BOUNDARY_SUPPORT_PROJECTOR_OUTER_UNDER_PENALTY_WEIGHT="${BOUNDARY_SUPPORT_PROJECTOR_OUTER_UNDER_PENALTY_WEIGHT:-0.75}" \
  BOUNDARY_SUPPORT_PROJECTOR_OUTER_EFFECTIVE_MIN="${BOUNDARY_SUPPORT_PROJECTOR_OUTER_EFFECTIVE_MIN:-0.10}" \
  BOUNDARY_SUPPORT_PROJECTOR_OUTER_OPACITY_FACTOR="${BOUNDARY_SUPPORT_PROJECTOR_OUTER_OPACITY_FACTOR:-0.84}" \
  BOUNDARY_SUPPORT_PROJECTOR_OUTER_SCALE_FACTOR="${BOUNDARY_SUPPORT_PROJECTOR_OUTER_SCALE_FACTOR:-0.94}" \
  setsid bash "$ROOT/tools/run_377_stageB_v248_boundary_component_support_serial.sh" \
  > "$NOHUP_LOG" 2>&1 &

PID=$!
echo "$PID" > "$LOG_DIR/launcher.pid"

{
  echo "RUN_ID=$RUN_ID"
  echo "PID=$PID"
  echo "GPU=$GPU"
  echo "LOG_DIR=$LOG_DIR"
  echo "NOHUP_LOG=$NOHUP_LOG"
  echo "STATUS_JSON=$LOG_DIR/status.json"
  echo "BASE_CKPT=${BASE_CKPT:-$BASE_V250_EXP/ckpt144950.pth}"
  echo "BASE_ITER=${BASE_ITER:-144950}"
  echo "START_BJT=$(TZ=Asia/Shanghai date '+%F %T BJT')"
  echo "EXPECTED_TRAIN_END_BJT=$(TZ=Asia/Shanghai date -d '+25 minutes' '+%F %T BJT')"
  echo "EXPECTED_RENDER_END_BJT=$(TZ=Asia/Shanghai date -d '+55 minutes' '+%F %T BJT')"
} | tee "$LOG_DIR/launch_info.txt"
