#!/usr/bin/env bash
set -euo pipefail

ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
cd "$ROOT"

RUN_ID="${RUN_ID:-stageB_v250_gapaware_component_support_9h_$(TZ=Asia/Shanghai date '+%Y%m%d_%H%M%S_bjt')}"
GPU="${GPU:-0}"
LOG_DIR="${LOG_DIR:-$ROOT/exp/stageB/logs/377_stageB_v250_gapaware_component_support_9h_${RUN_ID}}"
mkdir -p "$LOG_DIR"

NOHUP_LOG="$LOG_DIR/nohup.log"

env \
  EXPERIMENT_VERSION="v250" \
  EXPERIMENT_SLUG="gapaware_component_support_9h" \
  TRAIN_NAME="v250b_gapaware_component_support_9h" \
  LOG_PREFIX="377_stageB_v250_gapaware_component_support_9h" \
  RENDER_TAG="v250" \
  PURPOSE="v250 gap-aware component support: persist support metadata, reject outer-leak anchors, use screen-gap-aware support placement, run for nine-hour budget" \
  RUN_ID="$RUN_ID" \
  GPU="$GPU" \
  WAIT_FOR_FREE_GPU="${WAIT_FOR_FREE_GPU:-1}" \
  DO_RENDER="${DO_RENDER:-1}" \
  PYTHON_BIN="${PYTHON_BIN:-/opt/miniconda3/envs/ictrl/bin/python}" \
  STAGEB_ITERATIONS="${STAGEB_ITERATIONS:-18480}" \
  STAGEB_CHECKPOINT_STEPS="${STAGEB_CHECKPOINT_STEPS:-4620,9240,13860,18480}" \
  RENDER_CHECKPOINT_STEPS="${RENDER_CHECKPOINT_STEPS:-18480}" \
  TEST_INTERVAL="${TEST_INTERVAL:-20000}" \
  DENSIFY_FROM_STEP="${DENSIFY_FROM_STEP:-90}" \
  DENSIFY_UNTIL_STEP="${DENSIFY_UNTIL_STEP:-18480}" \
  DENSIFY_INTERVAL="${DENSIFY_INTERVAL:-120}" \
  DENSIFY_GRAD_THRESHOLD="${DENSIFY_GRAD_THRESHOLD:-0.00110}" \
  BINDING_MAPS="${BINDING_MAPS:-[layer,region,compact_semantic,body_prob,soft_prob,cloth_prob,semantic,temporal,thin,boundary_support]}" \
  MONTAGE_PANELS="${MONTAGE_PANELS:-gt render layer region body_prob cloth_prob compact_semantic boundary_support thin semantic}" \
  BOUNDARY_COMPONENT_SUPPORT_ACCUMULATE_PENDING="${BOUNDARY_COMPONENT_SUPPORT_ACCUMULATE_PENDING:-true}" \
  BOUNDARY_COMPONENT_SUPPORT_PENDING_MAX_VIEWS="${BOUNDARY_COMPONENT_SUPPORT_PENDING_MAX_VIEWS:-8}" \
  BOUNDARY_COMPONENT_SUPPORT_PENDING_MAX_POINTS="${BOUNDARY_COMPONENT_SUPPORT_PENDING_MAX_POINTS:-160}" \
  BOUNDARY_COMPONENT_SUPPORT_PENDING_VERBOSE="${BOUNDARY_COMPONENT_SUPPORT_PENDING_VERBOSE:-true}" \
  BOUNDARY_COMPONENT_SUPPORT_MAX_POINTS="${BOUNDARY_COMPONENT_SUPPORT_MAX_POINTS:-96}" \
  BOUNDARY_COMPONENT_SUPPORT_UNIQUE_PARENT="${BOUNDARY_COMPONENT_SUPPORT_UNIQUE_PARENT:-true}" \
  BOUNDARY_COMPONENT_SUPPORT_RESIDUAL_THRESHOLD="${BOUNDARY_COMPONENT_SUPPORT_RESIDUAL_THRESHOLD:-0.50}" \
  BOUNDARY_COMPONENT_SUPPORT_MIN_AREA="${BOUNDARY_COMPONENT_SUPPORT_MIN_AREA:-18}" \
  BOUNDARY_COMPONENT_SUPPORT_MAX_COMPONENTS="${BOUNDARY_COMPONENT_SUPPORT_MAX_COMPONENTS:-16}" \
  BOUNDARY_COMPONENT_SUPPORT_POINTS_PER_COMPONENT="${BOUNDARY_COMPONENT_SUPPORT_POINTS_PER_COMPONENT:-2}" \
  BOUNDARY_COMPONENT_SUPPORT_MAX_POINTS_PER_VIEW="${BOUNDARY_COMPONENT_SUPPORT_MAX_POINTS_PER_VIEW:-32}" \
  BOUNDARY_COMPONENT_SUPPORT_ANCHOR_SEARCH_RADIUS="${BOUNDARY_COMPONENT_SUPPORT_ANCHOR_SEARCH_RADIUS:-24.0}" \
  BOUNDARY_COMPONENT_SUPPORT_ANCHOR_FALLBACK_RADIUS="${BOUNDARY_COMPONENT_SUPPORT_ANCHOR_FALLBACK_RADIUS:-40.0}" \
  BOUNDARY_COMPONENT_SUPPORT_MAX_SCREEN_GAP="${BOUNDARY_COMPONENT_SUPPORT_MAX_SCREEN_GAP:-38.0}" \
  BOUNDARY_COMPONENT_SUPPORT_ANCHOR_BOUNDARY_MIN="${BOUNDARY_COMPONENT_SUPPORT_ANCHOR_BOUNDARY_MIN:-0.08}" \
  BOUNDARY_COMPONENT_SUPPORT_ANCHOR_OVER_MAX="${BOUNDARY_COMPONENT_SUPPORT_ANCHOR_OVER_MAX:-0.22}" \
  BOUNDARY_COMPONENT_SUPPORT_ANCHOR_OVER_REJECT_STRICT="${BOUNDARY_COMPONENT_SUPPORT_ANCHOR_OVER_REJECT_STRICT:-false}" \
  BOUNDARY_COMPONENT_SUPPORT_ANCHOR_OVER_PENALTY_WEIGHT="${BOUNDARY_COMPONENT_SUPPORT_ANCHOR_OVER_PENALTY_WEIGHT:-0.55}" \
  BOUNDARY_COMPONENT_SUPPORT_OFFSET_SCALE="${BOUNDARY_COMPONENT_SUPPORT_OFFSET_SCALE:-0.45}" \
  BOUNDARY_COMPONENT_SUPPORT_OFFSET_MIN="${BOUNDARY_COMPONENT_SUPPORT_OFFSET_MIN:-0.0008}" \
  BOUNDARY_COMPONENT_SUPPORT_OFFSET_MAX="${BOUNDARY_COMPONENT_SUPPORT_OFFSET_MAX:-0.026}" \
  BOUNDARY_COMPONENT_SUPPORT_SCREEN_GAP_OFFSET_SCALE="${BOUNDARY_COMPONENT_SUPPORT_SCREEN_GAP_OFFSET_SCALE:-0.72}" \
  BOUNDARY_COMPONENT_SUPPORT_SCREEN_GAP_RADIUS_MIN="${BOUNDARY_COMPONENT_SUPPORT_SCREEN_GAP_RADIUS_MIN:-2.0}" \
  BOUNDARY_COMPONENT_SUPPORT_SCREEN_GAP_RATIO_MAX="${BOUNDARY_COMPONENT_SUPPORT_SCREEN_GAP_RATIO_MAX:-2.0}" \
  BOUNDARY_COMPONENT_SUPPORT_SCREEN_GAP_OFFSET_MAX="${BOUNDARY_COMPONENT_SUPPORT_SCREEN_GAP_OFFSET_MAX:-0.026}" \
  BOUNDARY_COMPONENT_SUPPORT_CHILD_OPACITY_FACTOR="${BOUNDARY_COMPONENT_SUPPORT_CHILD_OPACITY_FACTOR:-0.48}" \
  BOUNDARY_COMPONENT_SUPPORT_CHILD_OPACITY_FLOOR="${BOUNDARY_COMPONENT_SUPPORT_CHILD_OPACITY_FLOOR:-0.012}" \
  BOUNDARY_COMPONENT_SUPPORT_CHILD_OPACITY_CEILING="${BOUNDARY_COMPONENT_SUPPORT_CHILD_OPACITY_CEILING:-0.24}" \
  BOUNDARY_COMPONENT_SUPPORT_CHILD_SCALE_FACTOR="${BOUNDARY_COMPONENT_SUPPORT_CHILD_SCALE_FACTOR:-0.34}" \
  BOUNDARY_SUPPORT_PROJECTOR_ENABLE="${BOUNDARY_SUPPORT_PROJECTOR_ENABLE:-true}" \
  BOUNDARY_SUPPORT_PROJECTOR_VERBOSE="${BOUNDARY_SUPPORT_PROJECTOR_VERBOSE:-true}" \
  BOUNDARY_SUPPORT_PROJECTOR_INNER_ENABLE="${BOUNDARY_SUPPORT_PROJECTOR_INNER_ENABLE:-false}" \
  BOUNDARY_SUPPORT_PROJECTOR_OUTER_ENABLE="${BOUNDARY_SUPPORT_PROJECTOR_OUTER_ENABLE:-true}" \
  BOUNDARY_SUPPORT_PROJECTOR_INNER_MAX_POINTS="${BOUNDARY_SUPPORT_PROJECTOR_INNER_MAX_POINTS:-0}" \
  BOUNDARY_SUPPORT_PROJECTOR_INNER_MAX_RATIO="${BOUNDARY_SUPPORT_PROJECTOR_INNER_MAX_RATIO:-0.0}" \
  BOUNDARY_SUPPORT_PROJECTOR_OUTER_MAX_POINTS="${BOUNDARY_SUPPORT_PROJECTOR_OUTER_MAX_POINTS:-48}" \
  BOUNDARY_SUPPORT_PROJECTOR_OUTER_MAX_RATIO="${BOUNDARY_SUPPORT_PROJECTOR_OUTER_MAX_RATIO:-0.0010}" \
  BOUNDARY_SUPPORT_PROJECTOR_OUTER_MAX_POINTS_PER_LINEAGE="${BOUNDARY_SUPPORT_PROJECTOR_OUTER_MAX_POINTS_PER_LINEAGE:-1}" \
  BOUNDARY_SUPPORT_PROJECTOR_OVER_THRESHOLD="${BOUNDARY_SUPPORT_PROJECTOR_OVER_THRESHOLD:-0.20}" \
  BOUNDARY_SUPPORT_PROJECTOR_BOUNDARY_THRESHOLD="${BOUNDARY_SUPPORT_PROJECTOR_BOUNDARY_THRESHOLD:-0.05}" \
  BOUNDARY_SUPPORT_PROJECTOR_OUTER_OPACITY_FACTOR="${BOUNDARY_SUPPORT_PROJECTOR_OUTER_OPACITY_FACTOR:-0.82}" \
  BOUNDARY_SUPPORT_PROJECTOR_OUTER_SCALE_FACTOR="${BOUNDARY_SUPPORT_PROJECTOR_OUTER_SCALE_FACTOR:-0.92}" \
  setsid bash "$ROOT/tools/run_377_stageB_v248_boundary_component_support_serial.sh" \
  > "$NOHUP_LOG" 2>&1 &

PID=$!
echo "$PID" > "$LOG_DIR/launcher.pid"

{
  echo "RUN_ID=$RUN_ID"
  echo "PID=$PID"
  echo "GPU=$GPU"
  echo "LOG_DIR=$LOG_DIR"
  echo "NOHUP_LOG=$NOHUP_LOG"
  echo "STATUS_JSON=$LOG_DIR/status.json"
  echo "START_BJT=$(TZ=Asia/Shanghai date '+%F %T BJT')"
  echo "EXPECTED_TRAIN_END_BJT=$(TZ=Asia/Shanghai date -d '+9 hours' '+%F %T BJT')"
} | tee "$LOG_DIR/launch_info.txt"
