#!/usr/bin/env bash
set -euo pipefail

ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
cd "$ROOT"

PYTHON_BIN="${PYTHON_BIN:-/opt/miniconda3/envs/ictrl/bin/python}"
GPU="${GPU:-0}"
RUN_ID="${RUN_ID:-v304_consistent_component_geometry_$(TZ=Asia/Shanghai date '+%Y%m%d_%H%M%S_bjt')}"
CPU_THREADS_PER_JOB="${CPU_THREADS_PER_JOB:-6}"

DATA_ROOT="${DATA_ROOT:-$ROOT/data/ZJUMoCap}"
BASE_EXP="${BASE_EXP:-$ROOT/exp/stageB/377_explicit_binding_v271_color_texture_only_v271_color_texture_only_20260517_150215_bjt}"
BASE_CKPT="${BASE_CKPT:-$BASE_EXP/ckpt136410.pth}"
BASE_ITER="${BASE_ITER:-136410}"

AUDIT_VIEWS="${AUDIT_VIEWS:-1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19,20,21,22,23}"
AUDIT_FRAMES="${AUDIT_FRAMES:-0,570,60}"
AUDIT_TOP_FRAMES="${AUDIT_TOP_FRAMES:-230}"
AUDIT_RUN_ID="${AUDIT_RUN_ID:-${RUN_ID}_audit_all_views_sparse}"
AUDIT_DIR="${AUDIT_DIR:-$ROOT/exp/stageB/logs/377_stageB_v304_consistent_component_audit_${AUDIT_RUN_ID}}"
AUDIT_LOG="$AUDIT_DIR/audit.log"
REUSE_AUDIT="${REUSE_AUDIT:-0}"

TRAIN_VIEWS_SPEC="${TRAIN_VIEWS_SPEC:-[1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19,20]}"
TRAIN_FRAMES_SPEC="${TRAIN_FRAMES_SPEC:-[0,570,60]}"
TRAIN_ITERS="${TRAIN_ITERS:-100}"
TRAIN_CHECKPOINT_STEPS="${TRAIN_CHECKPOINT_STEPS:-100}"
DO_TRAIN="${DO_TRAIN:-1}"
TRAIN_FEATURE_LR="${TRAIN_FEATURE_LR:-0.00010}"
TRAIN_TEXTURE_LR="${TRAIN_TEXTURE_LR:-0.00000020}"
TRAIN_TEX_LATENT_LR="${TRAIN_TEX_LATENT_LR:-0.0}"
TRAIN_TEXTURE_TRAINABLE_PATTERNS="${TRAIN_TEXTURE_TRAINABLE_PATTERNS:-[*]}"
TRAIN_LAMBDA_L1="${TRAIN_LAMBDA_L1:-0.040}"
TRAIN_LAMBDA_L1_FG="${TRAIN_LAMBDA_L1_FG:-0.110}"
TRAIN_LAMBDA_L1_BOUNDARY="${TRAIN_LAMBDA_L1_BOUNDARY:-0.050}"
TRAIN_LAMBDA_PERCEPTUAL="${TRAIN_LAMBDA_PERCEPTUAL:-0.010}"
TRAIN_GRAD_CLIP="${TRAIN_GRAD_CLIP:-0.0015}"
TRAIN_SCREEN_COLOR_PROTECT_ENABLE="${TRAIN_SCREEN_COLOR_PROTECT_ENABLE:-false}"
TRAIN_SCREEN_COLOR_PROTECT_BOUNDARY_WIDTH="${TRAIN_SCREEN_COLOR_PROTECT_BOUNDARY_WIDTH:-15}"
TRAIN_SCREEN_COLOR_PROTECT_OUTER_START="${TRAIN_SCREEN_COLOR_PROTECT_OUTER_START:-1}"
TRAIN_SCREEN_COLOR_PROTECT_OUTER_END="${TRAIN_SCREEN_COLOR_PROTECT_OUTER_END:-34}"
TRAIN_SCREEN_COLOR_PROTECT_RADIUS_PAD="${TRAIN_SCREEN_COLOR_PROTECT_RADIUS_PAD:-2}"
TRAIN_SCREEN_COLOR_PROTECT_MIN_RADIUS="${TRAIN_SCREEN_COLOR_PROTECT_MIN_RADIUS:-0.0}"
TRAIN_SCREEN_COLOR_PROTECT_MAX_POINTS="${TRAIN_SCREEN_COLOR_PROTECT_MAX_POINTS:-0}"
TRAIN_BOUNDARY_COLOR_PROTECT_ENABLE="${TRAIN_BOUNDARY_COLOR_PROTECT_ENABLE:-false}"
TRAIN_BOUNDARY_COLOR_PROTECT_VERBOSE="${TRAIN_BOUNDARY_COLOR_PROTECT_VERBOSE:-false}"

EXP_ROOT="${EXP_ROOT:-$ROOT/exp/stageB/377_explicit_binding_v304_consistent_component_geometry_refine_${RUN_ID}}"
LOG_DIR="${LOG_DIR:-$ROOT/exp/stageB/logs/377_explicit_binding_v304_consistent_component_geometry_refine_${RUN_ID}}"
EVENTS="$LOG_DIR/events.tsv"
STATUS_JSON="$LOG_DIR/status.json"

mkdir -p "$AUDIT_DIR" "$EXP_ROOT" "$LOG_DIR"

for required in "$PYTHON_BIN" "$BASE_EXP/.hydra/config.yaml" "$BASE_CKPT" "$DATA_ROOT"; do
  if [ ! -e "$required" ]; then
    echo "missing required path: $required" >&2
    exit 2
  fi
done

START_EPOCH="$(date +%s)"
EST_SECONDS="${EST_SECONDS:-5400}"
EST_END_EPOCH="$((START_EPOCH + EST_SECONDS))"
START_BJT="$(TZ=Asia/Shanghai date -d "@$START_EPOCH" '+%F %T BJT')"
EST_END_BJT="$(TZ=Asia/Shanghai date -d "@$EST_END_EPOCH" '+%F %T BJT')"

printf 'time_bjt\tphase\tdetail\n' > "$EVENTS"

write_status() {
  "$PYTHON_BIN" - "$STATUS_JSON" "$RUN_ID" "$GPU" "$1" "$2" "$START_BJT" "$EST_END_BJT" <<'PY' || true
import json
import sys
import time
from pathlib import Path

path, run_id, gpu, phase, detail, start_bjt, est_end_bjt = sys.argv[1:]
Path(path).write_text(json.dumps({
    "run_id": run_id,
    "gpu": gpu,
    "phase": phase,
    "detail": detail,
    "start_bjt": start_bjt,
    "est_end_bjt": est_end_bjt,
    "now_epoch": int(time.time()),
}, indent=2), encoding="utf-8")
PY
}

log_event() {
  printf '%s\t%s\t%s\n' "$(TZ=Asia/Shanghai date '+%F %T BJT')" "$1" "$2" | tee -a "$EVENTS"
  write_status "$1" "$2"
}

cat > "$LOG_DIR/run_info.txt" <<EOF
RUN_ID=$RUN_ID
START_BJT=$START_BJT
EST_END_BJT=$EST_END_BJT
GPU=$GPU
BASE_EXP=$BASE_EXP
BASE_CKPT=$BASE_CKPT
BASE_ITER=$BASE_ITER
DATA_ROOT=$DATA_ROOT
AUDIT_DIR=$AUDIT_DIR
AUDIT_VIEWS=$AUDIT_VIEWS
AUDIT_FRAMES=$AUDIT_FRAMES
AUDIT_TOP_FRAMES=$AUDIT_TOP_FRAMES
TRAIN_VIEWS_SPEC=$TRAIN_VIEWS_SPEC
TRAIN_FRAMES_SPEC=$TRAIN_FRAMES_SPEC
TRAIN_ITERS=$TRAIN_ITERS
TRAIN_CHECKPOINT_STEPS=$TRAIN_CHECKPOINT_STEPS
TRAIN_FEATURE_LR=$TRAIN_FEATURE_LR
TRAIN_TEXTURE_LR=$TRAIN_TEXTURE_LR
TRAIN_TEX_LATENT_LR=$TRAIN_TEX_LATENT_LR
TRAIN_TEXTURE_TRAINABLE_PATTERNS=$TRAIN_TEXTURE_TRAINABLE_PATTERNS
TRAIN_LAMBDA_L1=$TRAIN_LAMBDA_L1
TRAIN_LAMBDA_L1_FG=$TRAIN_LAMBDA_L1_FG
TRAIN_LAMBDA_L1_BOUNDARY=$TRAIN_LAMBDA_L1_BOUNDARY
TRAIN_LAMBDA_PERCEPTUAL=$TRAIN_LAMBDA_PERCEPTUAL
TRAIN_GRAD_CLIP=$TRAIN_GRAD_CLIP
TRAIN_SCREEN_COLOR_PROTECT_ENABLE=$TRAIN_SCREEN_COLOR_PROTECT_ENABLE
TRAIN_SCREEN_COLOR_PROTECT_BOUNDARY_WIDTH=$TRAIN_SCREEN_COLOR_PROTECT_BOUNDARY_WIDTH
TRAIN_SCREEN_COLOR_PROTECT_OUTER_START=$TRAIN_SCREEN_COLOR_PROTECT_OUTER_START
TRAIN_SCREEN_COLOR_PROTECT_OUTER_END=$TRAIN_SCREEN_COLOR_PROTECT_OUTER_END
TRAIN_SCREEN_COLOR_PROTECT_RADIUS_PAD=$TRAIN_SCREEN_COLOR_PROTECT_RADIUS_PAD
TRAIN_SCREEN_COLOR_PROTECT_MIN_RADIUS=$TRAIN_SCREEN_COLOR_PROTECT_MIN_RADIUS
TRAIN_SCREEN_COLOR_PROTECT_MAX_POINTS=$TRAIN_SCREEN_COLOR_PROTECT_MAX_POINTS
TRAIN_BOUNDARY_COLOR_PROTECT_ENABLE=$TRAIN_BOUNDARY_COLOR_PROTECT_ENABLE
TRAIN_BOUNDARY_COLOR_PROTECT_VERBOSE=$TRAIN_BOUNDARY_COLOR_PROTECT_VERBOSE
EXP_ROOT=$EXP_ROOT
LOG_DIR=$LOG_DIR

Goal:
  v304 fixes the v303 train/test mechanism mismatch. Component residual
  evidence is regenerated for train+test views on the same sparse frame grid
  used by short training, then both deformer geometry fidelity and renderer
  screen-space actuator require matching component records. Missing evidence
  disables the actuator instead of falling back to broad layer/region masks.
EOF

COMPONENT_CSV="$AUDIT_DIR/component_contributors.csv"
POINT_CSV="$AUDIT_DIR/point_contributors_all.csv"

if [ "$REUSE_AUDIT" = "1" ] && [ -s "$COMPONENT_CSV" ] && [ -s "$POINT_CSV" ]; then
  log_event "audit_reuse" "$AUDIT_DIR"
else
  log_event "audit_start" "views=$AUDIT_VIEWS frames=$AUDIT_FRAMES top_frames=$AUDIT_TOP_FRAMES"
  env \
    CUDA_VISIBLE_DEVICES="$GPU" \
    OMP_NUM_THREADS="$CPU_THREADS_PER_JOB" \
    MKL_NUM_THREADS="$CPU_THREADS_PER_JOB" \
    OPENBLAS_NUM_THREADS="$CPU_THREADS_PER_JOB" \
    NUMEXPR_NUM_THREADS="$CPU_THREADS_PER_JOB" \
    PYTHONUNBUFFERED=1 \
    PYTORCH_CUDA_ALLOC_CONF="${PYTORCH_CUDA_ALLOC_CONF:-max_split_size_mb:64}" \
    "$PYTHON_BIN" tools/audit_377_stageB_v274_contributors.py \
      --config-path "$BASE_EXP/.hydra/config.yaml" \
      --load-ckpt "$BASE_CKPT" \
      --out-dir "$AUDIT_DIR" \
      --dataset-root "$DATA_ROOT" \
      --eval-views "$AUDIT_VIEWS" \
      --eval-frames "$AUDIT_FRAMES" \
      --top-frames "$AUDIT_TOP_FRAMES" \
      --min-component-area 18 \
      --max-components-per-frame 8 \
      --component-top-points 8 \
      --top-points 160 \
      --candidate-points 96 \
      > "$AUDIT_LOG" 2>&1
  log_event "audit_done" "$AUDIT_DIR"
fi
for required in "$COMPONENT_CSV" "$POINT_CSV"; do
  if [ ! -s "$required" ]; then
    echo "audit did not produce required file: $required" >&2
    exit 3
  fi
done

log_event "refine_start" "component_required=true train_iters=$TRAIN_ITERS"
RUN_ID="$RUN_ID" \
PYTHON_BIN="$PYTHON_BIN" \
GPU="$GPU" \
CPU_THREADS_PER_JOB="$CPU_THREADS_PER_JOB" \
DATA_ROOT="$DATA_ROOT" \
BASE_EXP="$BASE_EXP" \
BASE_CKPT="$BASE_CKPT" \
BASE_ITER="$BASE_ITER" \
COMPONENT_CSV="$COMPONENT_CSV" \
POINT_CSV="$POINT_CSV" \
TRAIN_VIEWS_SPEC="$TRAIN_VIEWS_SPEC" \
TRAIN_FRAMES_SPEC="$TRAIN_FRAMES_SPEC" \
TRAIN_ITERS="$TRAIN_ITERS" \
TRAIN_CHECKPOINT_STEPS="$TRAIN_CHECKPOINT_STEPS" \
TRAIN_FEATURE_LR="$TRAIN_FEATURE_LR" \
TRAIN_TEXTURE_LR="$TRAIN_TEXTURE_LR" \
TRAIN_TEX_LATENT_LR="$TRAIN_TEX_LATENT_LR" \
TRAIN_TEXTURE_TRAINABLE_PATTERNS="$TRAIN_TEXTURE_TRAINABLE_PATTERNS" \
TRAIN_LAMBDA_L1="$TRAIN_LAMBDA_L1" \
TRAIN_LAMBDA_L1_FG="$TRAIN_LAMBDA_L1_FG" \
TRAIN_LAMBDA_L1_BOUNDARY="$TRAIN_LAMBDA_L1_BOUNDARY" \
TRAIN_LAMBDA_PERCEPTUAL="$TRAIN_LAMBDA_PERCEPTUAL" \
TRAIN_GRAD_CLIP="$TRAIN_GRAD_CLIP" \
TRAIN_SCREEN_COLOR_PROTECT_ENABLE="$TRAIN_SCREEN_COLOR_PROTECT_ENABLE" \
TRAIN_SCREEN_COLOR_PROTECT_BOUNDARY_WIDTH="$TRAIN_SCREEN_COLOR_PROTECT_BOUNDARY_WIDTH" \
TRAIN_SCREEN_COLOR_PROTECT_OUTER_START="$TRAIN_SCREEN_COLOR_PROTECT_OUTER_START" \
TRAIN_SCREEN_COLOR_PROTECT_OUTER_END="$TRAIN_SCREEN_COLOR_PROTECT_OUTER_END" \
TRAIN_SCREEN_COLOR_PROTECT_RADIUS_PAD="$TRAIN_SCREEN_COLOR_PROTECT_RADIUS_PAD" \
TRAIN_SCREEN_COLOR_PROTECT_MIN_RADIUS="$TRAIN_SCREEN_COLOR_PROTECT_MIN_RADIUS" \
TRAIN_SCREEN_COLOR_PROTECT_MAX_POINTS="$TRAIN_SCREEN_COLOR_PROTECT_MAX_POINTS" \
TRAIN_BOUNDARY_COLOR_PROTECT_ENABLE="$TRAIN_BOUNDARY_COLOR_PROTECT_ENABLE" \
TRAIN_BOUNDARY_COLOR_PROTECT_VERBOSE="$TRAIN_BOUNDARY_COLOR_PROTECT_VERBOSE" \
DO_TRAIN="$DO_TRAIN" \
PIPELINE_COMPONENT_REQUIRED=true \
EXP_ROOT="$EXP_ROOT" \
LOG_DIR="$LOG_DIR/refine" \
EST_SECONDS="${REFINE_EST_SECONDS:-3600}" \
bash tools/run_377_explicit_binding_v303_component_geometry_guarded_refine.sh \
  > "$LOG_DIR/refine_driver.log" 2>&1
log_event "refine_done" "$LOG_DIR/refine"

END_EPOCH="$(date +%s)"
END_BJT="$(TZ=Asia/Shanghai date -d "@$END_EPOCH" '+%F %T BJT')"
{
  echo "END_BJT=$END_BJT"
  echo "AUDIT_LOG=$AUDIT_LOG"
  echo "COMPONENT_CSV=$COMPONENT_CSV"
  echo "POINT_CSV=$POINT_CSV"
  echo "REFINE_LOG_DIR=$LOG_DIR/refine"
  echo "REFINE_SUMMARY=$LOG_DIR/refine/no_train_summary.tsv"
  echo "REFINE_TRAIN_SUMMARY=$LOG_DIR/refine/train_summary.tsv"
} >> "$LOG_DIR/run_info.txt"

log_event "all_done" "$END_BJT"
echo "EXP_ROOT=$EXP_ROOT"
echo "LOG_DIR=$LOG_DIR"
echo "AUDIT_DIR=$AUDIT_DIR"
echo "REFINE_SUMMARY=$LOG_DIR/refine/no_train_summary.tsv"
echo "REFINE_TRAIN_SUMMARY=$LOG_DIR/refine/train_summary.tsv"
echo "EST_END_BJT=$EST_END_BJT"
echo "END_BJT=$END_BJT"
