#!/usr/bin/env bash
set -euo pipefail

ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"

RUN_ID="${RUN_ID:-v397_persistent_support_bank_$(TZ=Asia/Shanghai date '+%Y%m%d_%H%M%S_bjt')}"
EXP_DIR="${EXP_DIR:-$ROOT/exp/formal/377_v397_persistent_support_bank_${RUN_ID}}"
LOG_DIR="${LOG_DIR:-$ROOT/exp/formal/logs/377_v397_persistent_support_bank_${RUN_ID}}"
HYDRA_RUN_DIR="${HYDRA_RUN_DIR:-$EXP_DIR/hydra_runtime}"

SELECTOR_NAME="${SELECTOR_NAME:-v397}"
SELECTOR_SUMMARY="${SELECTOR_SUMMARY:-$LOG_DIR/v397_raw_contour_checkpoint_summary.tsv}"
SELECTED_JSON="${SELECTED_JSON:-$LOG_DIR/v397_selected_checkpoint.json}"

SUPPORT_BANK_TRAIN_ENABLE="${SUPPORT_BANK_TRAIN_ENABLE:-true}"
SUPPORT_BANK_DIAGNOSTIC_ENABLE="${SUPPORT_BANK_DIAGNOSTIC_ENABLE:-true}"
SUPPORT_BANK_SELECTOR_ENABLE="${SUPPORT_BANK_SELECTOR_ENABLE:-true}"
SUPPORT_BANK_SUMMARY="${SUPPORT_BANK_SUMMARY:-$LOG_DIR/support_bank_summary.tsv}"

V392_UNDER_JACCARD_FLOOR="${V392_UNDER_JACCARD_FLOOR:-0.95}"
V392_OVER_JACCARD_FLOOR="${V392_OVER_JACCARD_FLOOR:-0.95}"
V392_ADOPTED_LOST_MAX="${V392_ADOPTED_LOST_MAX:-0}"

export RUN_ID EXP_DIR LOG_DIR HYDRA_RUN_DIR
export SELECTOR_NAME SELECTOR_SUMMARY SELECTED_JSON
export SUPPORT_BANK_TRAIN_ENABLE SUPPORT_BANK_DIAGNOSTIC_ENABLE SUPPORT_BANK_SELECTOR_ENABLE SUPPORT_BANK_SUMMARY
export V392_UNDER_JACCARD_FLOOR V392_OVER_JACCARD_FLOOR V392_ADOPTED_LOST_MAX

exec "$ROOT/tools/run_377_explicit_binding_v396_generalized_boundary_controller.sh" "$@"
