#!/usr/bin/env bash
set -euo pipefail

ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"

RUN_ID="${RUN_ID:-v324_interior_polish_signed_$(TZ=Asia/Shanghai date '+%Y%m%d_%H%M%S_bjt')}"

export RUN_ID
export TRAIN_ITERS="${TRAIN_ITERS:-50}"
export TRAIN_CHECKPOINT_STEPS="${TRAIN_CHECKPOINT_STEPS:-50}"
export FEATURE_LR="${FEATURE_LR:-0.000005}"
export TEXTURE_LR="${TEXTURE_LR:-0.0}"

export FG_L1_REGION_MODE="${FG_L1_REGION_MODE:-eroded_interior}"
export FG_L1_INTERIOR_ERODE_KERNEL_SIZE="${FG_L1_INTERIOR_ERODE_KERNEL_SIZE:-41}"
export LAMBDA_L1="${LAMBDA_L1:-0.0}"
export LAMBDA_L1_FG="${LAMBDA_L1_FG:-0.050}"
export LAMBDA_L1_BOUNDARY="${LAMBDA_L1_BOUNDARY:-0.0}"
export TEACHER_RENDER_DISTILL_ENABLE="${TEACHER_RENDER_DISTILL_ENABLE:-false}"
export LAMBDA_TEACHER_RENDER_DISTILL_BOUNDARY="${LAMBDA_TEACHER_RENDER_DISTILL_BOUNDARY:-0.0}"
export LAMBDA_TEACHER_RENDER_DISTILL_OUTER="${LAMBDA_TEACHER_RENDER_DISTILL_OUTER:-0.0}"
export LAMBDA_TEACHER_RENDER_DISTILL_INNER="${LAMBDA_TEACHER_RENDER_DISTILL_INNER:-0.0}"
export LAMBDA_TEACHER_RENDER_DISTILL_RAW_SUPPORT_BOUNDARY="${LAMBDA_TEACHER_RENDER_DISTILL_RAW_SUPPORT_BOUNDARY:-0.0}"
export LAMBDA_TEACHER_RENDER_DISTILL_RAW_SUPPORT_OUTER="${LAMBDA_TEACHER_RENDER_DISTILL_RAW_SUPPORT_OUTER:-0.0}"
export LAMBDA_TEACHER_RENDER_DISTILL_RAW_SUPPORT_INNER="${LAMBDA_TEACHER_RENDER_DISTILL_RAW_SUPPORT_INNER:-0.0}"

export BOUNDARY_COLOR_PROTECT_ENABLE="${BOUNDARY_COLOR_PROTECT_ENABLE:-true}"
export BOUNDARY_COLOR_PROTECT_VERBOSE="${BOUNDARY_COLOR_PROTECT_VERBOSE:-false}"
export SCREEN_COLOR_PROTECT_ENABLE="${SCREEN_COLOR_PROTECT_ENABLE:-true}"
export SCREEN_COLOR_PROTECT_BOUNDARY_WIDTH="${SCREEN_COLOR_PROTECT_BOUNDARY_WIDTH:-19}"
export SCREEN_COLOR_PROTECT_OUTER_START="${SCREEN_COLOR_PROTECT_OUTER_START:-1}"
export SCREEN_COLOR_PROTECT_OUTER_END="${SCREEN_COLOR_PROTECT_OUTER_END:-42}"
export SCREEN_COLOR_PROTECT_RADIUS_PAD="${SCREEN_COLOR_PROTECT_RADIUS_PAD:-6}"
export SCREEN_COLOR_PROTECT_MIN_RADIUS="${SCREEN_COLOR_PROTECT_MIN_RADIUS:-0.0}"
export SCREEN_COLOR_PROTECT_MAX_POINTS="${SCREEN_COLOR_PROTECT_MAX_POINTS:-0}"

export STATIC_COLOR_PROTECT_ENABLE="${STATIC_COLOR_PROTECT_ENABLE:-true}"
export STATIC_COLOR_PROTECT_MAX_POINT_CSV_POINTS="${STATIC_COLOR_PROTECT_MAX_POINT_CSV_POINTS:-1024}"
export STATIC_COLOR_PROTECT_MIN_ABS_SIGNED_SCORE="${STATIC_COLOR_PROTECT_MIN_ABS_SIGNED_SCORE:-65.0}"
export STATIC_COLOR_PROTECT_MIN_VISIBLE_HITS="${STATIC_COLOR_PROTECT_MIN_VISIBLE_HITS:-60}"

export EXP_ROOT="${EXP_ROOT:-$ROOT/exp/stageB/377_explicit_binding_v324_interior_polish_signed_${RUN_ID}}"
export LOG_DIR="${LOG_DIR:-$ROOT/exp/stageB/logs/377_explicit_binding_v324_interior_polish_signed_${RUN_ID}}"

exec bash "$ROOT/tools/run_377_explicit_binding_v321_teacher_locked_paired_signed_train.sh"
