#!/usr/bin/env bash
set -euo pipefail

ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"

RUN_ID="${RUN_ID:-v399_diagnostic_sweep_$(TZ=Asia/Shanghai date '+%Y%m%d_%H%M%S_bjt')}"
EXP_DIR="${EXP_DIR:-$ROOT/exp/formal/377_v399_diagnostic_sweep_${RUN_ID}}"
LOG_DIR="${LOG_DIR:-$ROOT/exp/formal/logs/377_v399_diagnostic_sweep_${RUN_ID}}"
HYDRA_RUN_DIR="${HYDRA_RUN_DIR:-$EXP_DIR/hydra_runtime}"

SELECTOR_NAME="${SELECTOR_NAME:-v399}"
SELECTOR_SUMMARY="${SELECTOR_SUMMARY:-$LOG_DIR/v399_raw_contour_checkpoint_summary.tsv}"
SELECTED_JSON="${SELECTED_JSON:-$LOG_DIR/v399_selected_checkpoint.json}"
SELECTOR_SCHEMA_NAME="${SELECTOR_SCHEMA_NAME:-v399_diagnostic_sweep}"

SUPPORT_BANK_TRAIN_ENABLE="${SUPPORT_BANK_TRAIN_ENABLE:-true}"
SUPPORT_BANK_DIAGNOSTIC_ENABLE="${SUPPORT_BANK_DIAGNOSTIC_ENABLE:-true}"
SUPPORT_BANK_SELECTOR_ENABLE="${SUPPORT_BANK_SELECTOR_ENABLE:-true}"
SUPPORT_BANK_SUMMARY="${SUPPORT_BANK_SUMMARY:-$LOG_DIR/support_bank_summary.tsv}"

BAD_FRAME_SELECTOR_ENABLE="${BAD_FRAME_SELECTOR_ENABLE:-true}"
BAD_FRAME_SELECTOR_MODE="${BAD_FRAME_SELECTOR_MODE:-penalty}"
BAD_FRAME_OUTER_HARD_VETO="${BAD_FRAME_OUTER_HARD_VETO:-8.0}"
BAD_FRAME_HARD_HARD_VETO="${BAD_FRAME_HARD_HARD_VETO:-0.0005}"
BAD_FRAME_HARD_PENALTY="${BAD_FRAME_HARD_PENALTY:-0.00005}"
BAD_FRAME_IMAGE_SUMMARY="${BAD_FRAME_IMAGE_SUMMARY:-$LOG_DIR/bad_frame_image_summary.tsv}"

STABLE_WINDOW_TARGET="${STABLE_WINDOW_TARGET:-3}"
V392_ADOPTED_LOST_MAX="${V392_ADOPTED_LOST_MAX:-0}"

V399_OVER_EFFECTIVE_RATIO="${V399_OVER_EFFECTIVE_RATIO:-0.50}"
V399_OVER_NEW_ONLY_RATIO="${V399_OVER_NEW_ONLY_RATIO:-0.46}"
V399_UNDER_EFFECTIVE_RATIO="${V399_UNDER_EFFECTIVE_RATIO:-0.30}"
V399_UNDER_NEW_ONLY_RATIO="${V399_UNDER_NEW_ONLY_RATIO:-0.24}"

EXTRA_TRAIN_ARGS="${EXTRA_TRAIN_ARGS:-}"
EXTRA_TRAIN_ARGS="$EXTRA_TRAIN_ARGS ++opt.boundary_support_bank_under_max_effective_ratio=0.30"
EXTRA_TRAIN_ARGS="$EXTRA_TRAIN_ARGS ++opt.boundary_support_bank_under_max_new_only_ratio=0.24"
EXTRA_TRAIN_ARGS="$EXTRA_TRAIN_ARGS ++opt.boundary_support_bank_over_max_effective_ratio=$V399_OVER_EFFECTIVE_RATIO"
EXTRA_TRAIN_ARGS="$EXTRA_TRAIN_ARGS ++opt.boundary_support_bank_over_max_new_only_ratio=$V399_OVER_NEW_ONLY_RATIO"

export RUN_ID EXP_DIR LOG_DIR HYDRA_RUN_DIR
export SELECTOR_NAME SELECTOR_SUMMARY SELECTED_JSON SELECTOR_SCHEMA_NAME
export SUPPORT_BANK_TRAIN_ENABLE SUPPORT_BANK_DIAGNOSTIC_ENABLE SUPPORT_BANK_SELECTOR_ENABLE SUPPORT_BANK_SUMMARY
export BAD_FRAME_SELECTOR_ENABLE BAD_FRAME_SELECTOR_MODE BAD_FRAME_OUTER_HARD_VETO BAD_FRAME_HARD_HARD_VETO
export BAD_FRAME_HARD_PENALTY BAD_FRAME_IMAGE_SUMMARY
export V399_UNDER_EFFECTIVE_RATIO V399_UNDER_NEW_ONLY_RATIO V399_OVER_EFFECTIVE_RATIO V399_OVER_NEW_ONLY_RATIO
export STABLE_WINDOW_TARGET V392_ADOPTED_LOST_MAX EXTRA_TRAIN_ARGS

exec "$ROOT/tools/run_377_explicit_binding_v396_generalized_boundary_controller.sh" "$@"
