#!/usr/bin/env bash
set -euo pipefail

ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
PYTHON_BIN="${PYTHON_BIN:-/opt/miniconda3/envs/3dgs-avatar/bin/python}"
RUN_ID="${RUN_ID:-$(TZ=Asia/Shanghai date '+%Y%m%d_%H%M%S_bjt')}"
BASE_EXP="$ROOT/exp/stageA2/377_multiview_explicit_hq_rootfix_resume_v193a_v192a_adaptive_stable_texture_20260508_v193a_adaptive_stable_texture"
EXP_DIR="${1:-$ROOT/exp/stageA2/377_multiview_explicit_hq_rootfix_resume_v197a_v193a_boundary_substrate_$RUN_ID}"
START_CKPT="${2:-$BASE_EXP/best_ckpt.pth}"
ITERATIONS="${3:-1500}"

if [ "$#" -gt 0 ] && [[ "$1" != --* ]]; then shift; fi
if [ "$#" -gt 0 ] && [[ "$1" != --* ]]; then shift; fi
if [ "$#" -gt 0 ] && [[ "$1" != --* ]]; then shift; fi

mkdir -p "$EXP_DIR"
cd "$ROOT"

exec env PYTHONUNBUFFERED=1 "$PYTHON_BIN" train.py \
  --config-path "$BASE_EXP/.hydra" \
  --config-name config \
  mode=train \
  "dataset.root_dir=$ROOT/data/ZJUMoCap" \
  "dataset.preload=false" \
  "dataset.train_views=[21,22,23]" \
  "dataset.val_views=[21,22,23]" \
  "dataset.test_views.view=[21,22,23]" \
  "dataset.train_frames=[0,570,1]" \
  "dataset.val_frames=[0,570,30]" \
  "dataset.test_frames.view=[0,570,30]" \
  "start_checkpoint=$START_CKPT" \
  "exp_dir=$EXP_DIR" \
  "wandb_disable=true" \
  "++resume.restore_converter_optimizer_state=false" \
  "++resume.restore_converter_scheduler_state=false" \
  "++resume.partial_converter_missing_keys_allow_patterns=[]" \
  "++resume.disable_densify_on_resume=true" \
  "++resume.disable_opacity_reset_on_resume=true" \
  "++resume.require_no_densify_on_resume=true" \
  "opt.iterations=$ITERATIONS" \
  "pipeline.pose_noise=0.0" \
  "model.pose_correction.delay=1" \
  "++model.pose_correction.train_root_orient=false" \
  "++model.pose_correction.train_pose_body=true" \
  "++model.pose_correction.train_pose_hand=false" \
  "++model.pose_correction.train_trans=false" \
  "++model.pose_correction.train_betas=false" \
  "++model.pose_correction.pose_body_train_joint_ids=[12,13,14,15,16,17]" \
  "opt.position_lr_init=0.0" \
  "opt.position_lr_final=0.0" \
  "opt.feature_lr=0.0" \
  "opt.opacity_lr=0.0" \
  "opt.scaling_lr=0.0" \
  "opt.rotation_lr=0.0" \
  "opt.rigid_lr=0.0" \
  "opt.non_rigid_lr=0.0" \
  "opt.nr_latent_lr=0.0" \
  "opt.pose_correction_lr=6.0e-07" \
  "opt.texture_lr=0.0" \
  "opt.tex_latent_lr=0.0" \
  "++opt.texture_trainable_name_patterns=[__freeze_texture_no_match__]" \
  "++opt.camera_affine_enable=false" \
  "++opt.camera_affine_lr=0.0" \
  "++opt.camera_geometry_enable=true" \
  "++opt.camera_geometry_train_camera_ids=[21,22,23]" \
  "++opt.camera_geometry_max_camera_id=23" \
  "++opt.camera_geometry_strength=[0.00,1,0.25,300,0.55,900,0.80]" \
  "++opt.camera_geometry_rot_max_deg=0.28" \
  "++opt.camera_geometry_trans_max=0.006" \
  "++opt.camera_geometry_rot_reg_weight=1.0" \
  "++opt.camera_geometry_trans_reg_weight=1.0" \
  "++opt.camera_geometry_lr=5.0e-05" \
  "++opt.lambda_camera_geometry_reg=0.026" \
  "++opt.boundary_aware_boundary_opacity_residual_scale=0.58" \
  "++opt.boundary_aware_boundary_scaling_residual_scale=0.34" \
  "++opt.boundary_opacity_residual_lr=8.0e-05" \
  "++opt.boundary_scaling_residual_lr=2.2e-05" \
  "++opt.lambda_boundary_opacity_residual_reg=0.0008" \
  "++opt.lambda_boundary_scaling_residual_reg=0.00025" \
  "++opt.lambda_boundary_opacity_residual_smooth=0.0010" \
  "++opt.lambda_boundary_scaling_residual_smooth=0.0008" \
  "++opt.latent_weight_decay=0.0" \
  "opt.lambda_pose=0.30" \
  "opt.lambda_l1=0.022" \
  "++opt.lambda_l1_fg=0.074" \
  "opt.lambda_perceptual=0.22" \
  "opt.lambda_dssim=0.0" \
  "++opt.perceptual_masked=true" \
  "++opt.perceptual_mask_dilate=3" \
  "++opt.perceptual_crop_pad=20" \
  "++opt.perceptual_exclude_boundary_width=12" \
  "++opt.perceptual_adaptive_boundary_exclude_enable=true" \
  "++opt.perceptual_adaptive_boundary_width=23" \
  "++opt.perceptual_adaptive_error_threshold=0.40" \
  "++opt.perceptual_adaptive_error_width=0.18" \
  "++opt.perceptual_adaptive_edge_protect=0.42" \
  "++opt.perceptual_adaptive_reliability_power=1.30" \
  "++opt.perceptual_adaptive_min_weight=0.06" \
  "++opt.perceptual_stable_erode_kernel_size=3" \
  "++opt.perceptual_stable_min_pixels=96" \
  "++opt.perceptual_stable_fallback_to_source=false" \
  "++opt.patch_perceptual_min_mask_coverage=0.24" \
  "++opt.face_perceptual_exclude_boundary_width=6" \
  "++opt.face_perceptual_adaptive_boundary_width=13" \
  "++opt.face_perceptual_adaptive_error_threshold=0.44" \
  "++opt.face_perceptual_stable_erode_kernel_size=1" \
  "++opt.face_perceptual_stable_min_pixels=24" \
  "++opt.face_perceptual_stable_fallback_to_source=true" \
  "++opt.face_patch_perceptual_min_mask_coverage=0.16" \
  "++opt.shoulder_arm_perceptual_exclude_boundary_width=13" \
  "++opt.shoulder_arm_perceptual_adaptive_boundary_width=27" \
  "++opt.shoulder_arm_perceptual_adaptive_error_threshold=0.38" \
  "++opt.shoulder_arm_perceptual_stable_erode_kernel_size=3" \
  "++opt.shoulder_arm_perceptual_stable_min_pixels=32" \
  "++opt.shoulder_arm_perceptual_stable_fallback_to_source=false" \
  "++opt.shoulder_arm_patch_perceptual_min_mask_coverage=0.26" \
  "++opt.upper_torso_perceptual_exclude_boundary_width=12" \
  "++opt.upper_torso_perceptual_adaptive_boundary_width=25" \
  "++opt.upper_torso_perceptual_adaptive_error_threshold=0.40" \
  "++opt.upper_torso_perceptual_stable_erode_kernel_size=3" \
  "++opt.upper_torso_perceptual_stable_min_pixels=32" \
  "++opt.upper_torso_perceptual_stable_fallback_to_source=false" \
  "++opt.upper_torso_patch_perceptual_min_mask_coverage=0.24" \
  "++opt.upper_torso_core_perceptual_exclude_boundary_width=8" \
  "++opt.upper_torso_core_perceptual_adaptive_boundary_width=17" \
  "++opt.upper_torso_core_perceptual_adaptive_error_threshold=0.42" \
  "++opt.upper_torso_core_perceptual_stable_erode_kernel_size=1" \
  "++opt.upper_torso_core_perceptual_stable_min_pixels=24" \
  "++opt.upper_torso_core_patch_perceptual_min_mask_coverage=0.20" \
  "++opt.waist_perceptual_exclude_boundary_width=12" \
  "++opt.waist_perceptual_adaptive_boundary_width=25" \
  "++opt.waist_perceptual_adaptive_error_threshold=0.39" \
  "++opt.waist_perceptual_stable_erode_kernel_size=3" \
  "++opt.waist_perceptual_stable_min_pixels=32" \
  "++opt.waist_perceptual_stable_fallback_to_source=false" \
  "++opt.waist_patch_perceptual_min_mask_coverage=0.24" \
  "++opt.lambda_l1_boundary=0.090" \
  "opt.lambda_mask=0.0" \
  "++opt.lambda_mask_boundary=0.010" \
  "++opt.lambda_mask_boundary_hard=0.016" \
  "++opt.lambda_silhouette_outer=0.006" \
  "++opt.lambda_silhouette_outer_shell=0.010" \
  "++opt.lambda_silhouette_shoulder_arm_outer_shell=0.014" \
  "++opt.lambda_silhouette_upper_torso_outer_shell=0.014" \
  "++opt.lambda_silhouette_inner=0.004" \
  "++opt.silhouette_outer_ring_width=9" \
  "++opt.silhouette_outer_shell_start_width=1" \
  "++opt.silhouette_outer_shell_end_width=17" \
  "++opt.silhouette_inner_ring_width=7" \
  "++opt.boundary_band_width=11" \
  "++opt.lambda_edge_face=0.0" \
  "++opt.lambda_edge_shoulder_arm=0.0" \
  "++opt.lambda_edge_waist=0.0" \
  "++opt.lambda_detail_face=0.0" \
  "++opt.lambda_detail_shoulder_arm=0.0" \
  "++opt.lambda_detail_waist=0.0" \
  "++opt.lambda_detail_face_luma_dog=0.0" \
  "++opt.lambda_detail_shoulder_arm_luma_dog=0.0" \
  "++opt.lambda_detail_waist_luma_dog=0.0" \
  "++opt.lambda_detail_upper_torso_luma_dog=0.0" \
  "++opt.lambda_detail_upper_torso_core_luma_dog=0.0" \
  "++opt.lambda_perceptual_face=0.090" \
  "++opt.lambda_perceptual_shoulder_arm=0.035" \
  "++opt.lambda_perceptual_waist=0.026" \
  "++opt.lambda_perceptual_face_patch=0.050" \
  "++opt.lambda_perceptual_shoulder_arm_patch=0.028" \
  "++opt.lambda_perceptual_waist_patch=0.022" \
  "++opt.lambda_perceptual_upper_torso_patch=0.030" \
  "++opt.lambda_perceptual_upper_torso_core_patch=0.030" \
  "++opt.reliable_view_supervision_enable=true" \
  "++opt.reliable_view_camera_quality_weights={21:0.55,22:0.82,23:1.18}" \
  "++opt.reliable_view_default_highfreq_weight=0.75" \
  "++opt.reliable_view_unknown_highfreq_weight=0.75" \
  "++opt.reliable_view_highfreq_power=1.30" \
  "++opt.reliable_view_highfreq_min_weight=0.35" \
  "++opt.reliable_view_highfreq_max_weight=1.22" \
  "++opt.reliable_view_apply_global_perceptual=true" \
  "++opt.reliable_view_apply_patch_perceptual=true" \
  "++opt.reliable_view_apply_region_perceptual=true" \
  "++opt.reliable_view_apply_edge=false" \
  "++opt.reliable_view_apply_detail=false" \
  "++opt.reliable_view_apply_luma_dog=false" \
  "++opt.contour_uncertainty_min_weight=0.45" \
  "opt.grad_clip=0.010" \
  "++opt.train_sample_camera_weights={21:0.90,22:1.00,23:1.15}" \
  "++opt.train_sample_camera_min_prob=0.27" \
  "++opt.train_sample_camera_max_prob=0.40" \
  "++opt.photometric_contour_debug_interval=200" \
  "test_interval=300" \
  "test_iterations=[300,600,900,1200,1500]" \
  "save_iterations=[600,1200,1500]" \
  "checkpoint_iterations=[300,600,900,1200,1500]" \
  "++validation_image_log_limit=0" \
  "$@"
